env: "docker"

postgres:
  host: "postgres"
  port: 5432
  user: "admin"
  password: "admin"
  dbname: "events"
  sslmode: "disable"

kafka:
  brokers:
    - "kafka:9092"
  topic: "content_events"

http:
  host: "0.0.0.0"
  port: 8080
