services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - events-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d events"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - events-net

  kafka:
    image: redpandadata/redpanda:v23.3.12
    container_name: kafka
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --node-id=1
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - events-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: redpanda
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - events-net

  events-app:
    build: .
    container_name: eventsService-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    command: ["/app/eventsService"]
    environment:
      CONFIG_PATH: /config/config.yaml
      POSTGRES_DSN: postgres://admin:admin@postgres:5432/events?sslmode=disable
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: content_events
    volumes:
      - ./config:/config:ro
    ports:
      - "8080:8080"
      - "50051:50051"
    networks:
      - events-net

  analytics-app:
    build: .
    container_name: analytics-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    command: ["/app/analyticsService"]
    environment:
      CONFIG_PATH: /config/analytics.yaml
      POSTGRES_DSN: postgres://admin:admin@postgres:5432/analytics?sslmode=disable

      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: content_events
      REDIS_ADDR: redis:6379
    volumes:
      - ./config:/config:ro
    networks:
      - events-net

volumes:
  redis_data:
  postgres_data:

networks:
  events-net:
    driver: bridge
