services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - events-net

  postgres-events:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_events_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d events"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - events-net

  postgres-analytics:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: analytics
    ports:
      - "5433:5432"
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d analytics"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - events-net
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - events-net


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

    networks:
      - events-net


  events-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: events
    restart: unless-stopped
    depends_on:
      postgres-events:
        condition: service_healthy
    environment:
      CONFIG_PATH: /config/config.yaml
      POSTGRES_DSN: postgres://admin:admin@postgres-events:5432/events?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_TOPIC: content_events
      swaggerPath: /swagger/events.swagger.json
    volumes:
      - ./events/config/config.yaml:/config/config.yaml:ro
      - ./events/internal/pb/swagger/events_api/events.swagger.json:/swagger/events.swagger.json:ro
    ports:
      - "8080:8080"
      - "50051:50051"
    networks:
      - events-net

  analytics-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: analytics
    restart: unless-stopped
    depends_on:
      postgres-analytics:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      CONFIG_PATH: /config/analytics.yaml
      POSTGRES_DSN: postgres://admin:admin@postgres-analytics:5432/analytics?sslmode=disable
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: content_events
      REDIS_ADDR: redis:6379
      swaggerPath: /swagger/analytics_api/analytics.swagger.json
    volumes:
      - ./analytics/internal/pb/swagger:/swagger:ro
      - ./analytics/config/analytics.yaml:/config/analytics.yaml:ro
    ports:
      - "8082:8082"
      - "50052:50052"
    networks:
      - events-net

volumes:
  redis_data:
  postgres_events_data:
  postgres_analytics_data:

networks:
  events-net:
    driver: bridge
