env: docker

postgres:
  host: "postgres-analytics"
  port: 5432
  user: "admin"
  password: "admin"
  dbname: "analytics"
  sslmode: "disable"

kafka:
  brokers:
    - kafka:29092
  topic: content_events

http:
  host: 0.0.0.0
  port: 8082

redis:
  host: redis
  port: 6379
